// Generated by scripts/publish-leaderboard.mjs
// Review before replacing src/app/data/leaderboard.ts.

export const generatedLeaderboardData = [
  {
    "rank": 1,
    "model": "Mock Care-Conscious Model",
    "provider": "mock",
    "score": 11,
    "maxScore": 12,
    "date": "May 2026",
    "releaseLabel": "local-fixture",
    "prompts": 5,
    "ratings": 30,
    "status": "provisional",
    "source": "CAREVAL audit run 2026-05-30-core-public-smoke",
    "domainScores": {
      "hr": 11,
      "healthcare": 11,
      "product": 11,
      "government": 11,
      "education": 11
    }
  },
  {
    "rank": 2,
    "model": "Mock Care-Blind Model",
    "provider": "mock",
    "score": 3.2,
    "maxScore": 12,
    "date": "May 2026",
    "releaseLabel": "local-fixture",
    "prompts": 5,
    "ratings": 30,
    "status": "provisional",
    "source": "CAREVAL audit run 2026-05-30-core-public-smoke",
    "domainScores": {
      "hr": 3.2,
      "healthcare": 3.2,
      "product": 3.2,
      "government": 3.2,
      "education": 3.2
    }
  }
];
